class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'moonCakeCalculator': 'Moon Cake Calculator',
      'lblWhichType': 'Which type of moon cake would you like to make?',
      'lblWhichFillingType': 'Which type of filling would you like to use?',
      'lblwhichDoughRecipe': 'Which dough recipe do you want to use?',
      'lblwhichFillingRecipe': 'Which filling recipe do you want to use?',
      'type': 'Type',
      'type_list_title': 'Types',
      'recipe_list_title': 'Recipes',
      'type_details_title': 'Type Details',
      'cantonese': 'Cantonese-style',
      'snowSkin': 'Snow skin',
      'selectRecipe': 'Select recipe',
      'doughRecipe': 'Dough Recipe',
      'fillingRecipe': 'Filling Recipe',
      'viewDetails': 'View Details',
      'fillingType': 'Filling type',
      'redBean': 'Red Bean',
      'lotusSeeds': 'Lotus Seed',
      'fiveNuts': 'Five Nuts',
      'ratio': 'Pastry/Filling Ratio',
      'size': 'Size (g)',
      'qty': 'Qty',
      'calculate': 'Calculate',
      'totalWeight': 'Total Weight:',
      'pastryWeight': 'Pastry Weight:',
      'fillingWeight': 'Filling Weight:',
      'moonCakeWeight': 'Moon Cake Weight',
      'goToList': 'Go to List',
      'recipes': 'Recipes',
      'addRecipe': 'Add Recipe',
      'name': 'Name',
      'style': 'Style',
      'ingredients': 'Ingredients',
      'ingredient': 'Ingredient',
      'amount': 'Amount',
      'save': 'Save',
      'saveTask': 'Save Task',
      'cancel': 'Cancel',
      'addIngredient': 'Add ingredient',
      'recipeSavedSuccessfully': 'Recipe saved successfully.',
      'createdLocalRecipesFile': 'Created local recipes file.',
      'addAtLeastOneIngredient': 'Add at least one ingredient.',
      'failedToSaveRecipe': 'Failed to save recipe:',
      'dough': 'Dough',
      'filling': 'Filling',
      'home': 'Home',
      'tasks': 'Tasks',
      'profile': 'Profile',
      'language': 'Language',
      'english': 'English',
      'chinese': 'Chinese',
      'noRecipesFound': 'No recipes found',
      'noRecipesAvailable': 'No recipes available',
      'noRecipesForType': 'No recipes found, please add recipe for {type}',
      'back': 'Back',
      'close': 'Close',
      'noTasks': 'No tasks yet. Create one to get started!',
      'calculationResult': 'Calculation Result',
      'noIngredients': 'No ingredients.',
      'description': 'Description',
      'delete_recipe': 'Delete Recipe',
      'confirm_delete_recipe': 'Are you sure you want to delete {recipe_name}?',
      'comment': 'Comment',
      'rating': 'Rating',
      'no_comment': 'No comment',
      'no_rating': 'Not rated yet',
      'reference_url': 'Reference URL',
      'dough_type': 'Dough Type',
      'filling_type': 'Filling Type',
      'goodMorning': 'Good Morning',
      'goodAfternoon': 'Good Afternoon',
      'goodEvening': 'Good Evening',
      'recipeSaveSuccessfulMsg': 'Recipe saved successfully.',
      'category': 'Category',
      'unknown': 'Unknown',
      'quantity': 'Quantity',
      'created_at': 'Created',
      'used_in_tasks': 'Used in {count} task(s)',
      'matched_dough_types': 'Matched dough types',
      'matched_filling_types': 'Matched filling types',
      'validRecipeNameMsg': 'Please enter a valid recipe name.',
      'validRecipeTypeMsg': 'Please select a valid dough type.',
      'validFillingTypeMsg': 'Please select a valid filling type.',
      'validDoughRecipeMsg': 'Please select a dough recipe.',
      'validFillingRecipeMsg': 'Please select a filling recipe.',
      'validIngredientNameMsg': 'Please enter a valid ingredient name.',
      'validIngredientAmountMsg': 'Please enter a valid ingredient amount.',
      'validMatchedDoughTypesMsg': 'Please select at least one matched dough type.',
      'validMatchedFillingTypesMsg': 'Please select at least one matched filling type.',
      'invalidNumber': 'Invalid number.',
      'calculating': 'Calculating...',
      'calculateSave': 'Calculating and saving',
      'msgNoRecipe': 'No recipes available',
      'changes_saved': 'Changes saved successfully.',
      'failed_to_update_changes': 'Failed to update changes',
      'confirm_delete_task': 'Are you sure you want to delete this task?',
      'delete_task': 'Delete Task',
      'selectImage': 'Select Image',
      'delete': 'Delete',
      'confirm_delete': 'Are you sure you want to delete {name}?',
      'no_image_uploaded': 'No image uploaded',
      'completed': 'Completed',
      'enter_comment': 'Enter your comment here...',

    },
    'zh': {
      'moonCakeCalculator': '月饼计算器',
      'lblWhichType': '您想制作哪种类型的月饼？',
      'lblWhichFillingType': '您想使用哪种馅料类型？',
      'lblwhichDoughRecipe': '您想使用哪种饼皮食谱？',
      'lblwhichFillingRecipe': '您想使用哪种馅料食谱？',
      'type': '类型',
      'type_list_title': '食谱类型',
      'recipe_list_title': '食谱',
      'type_details_title': '类型详情',
      'cantonese': '广式月饼',
      'snowSkin': '冰皮月饼',
      'selectRecipe': '选择食谱',
      'doughRecipe': '饼皮食谱',
      'fillingRecipe': '馅料食谱',
      'viewDetails': '食谱详情',
      'fillingType': '馅料类型',
      'noFillingRecipes': '无馅料食谱可用，请添加馅料食谱。',
      'noDoughRecipes': '无饼皮食谱可用，请添加饼皮食谱。',
      'redBean': '红豆',
      'lotusSeeds': '莲子',
      'fiveNuts': '五仁',
      'ratio': '饼皮/馅料比例',
      'size': '月饼大小',
      'qty': '数量',
      'calculate': '计算饼皮及馅料配方',
      'totalWeight': '总重量:',
      'pastryWeight': '酥皮重量:',
      'fillingWeight': '馅料重量:',
      'moonCakeWeight': '月饼详情',
      'goToList': '转到列表',
      'recipes': '食谱',
      'addRecipe': '添加食谱',
      'name': '名称',
      'style': '风格',
      'ingredients': '配料',
      'ingredient': '配料',
      'amount': '数量',
      'save': '保存',
      'saveTask': '保存任务',
      'cancel': '取消',
      'addIngredient': '添加配料',
      'recipeSavedSuccessfully': '食谱保存成功。',
      'createdLocalRecipesFile': '创建本地食谱文件。',
      'addAtLeastOneIngredient': '至少添加一种原料。',
      'failedToSaveRecipe': '保存食谱失败：',
      'dough': '饼皮',
      'filling': '馅料',
      'home': '首页',
      'tasks': '任务',
      'profile': '个人资料',
      'language': '语言',
      'english': '英文',
      'chinese': '中文',
      'noRecipesFound': '未找到食谱',
      'noRecipesAvailable': '没有可用的食谱',
      'noRecipesForType': '未找到食谱，请为 {type} 添加食谱',
      'back': '返回',
      'close': '关闭',
      'noTasks': '还没有任务。创建一个任务开始！',
      'calculationResult': '配方计算结果',
      'noIngredients': '没有配方。',
      'description': '描述',
      'delete_recipe': '删除食谱',
      'confirm_delete_recipe': '您确定要删除 {recipe_name} 吗？',
      'comment': '评论',
      'rating': '评分',
      'no_comment': '暂无评论',
      'no_rating': '尚未评分',
      'reference_url': '参考网址',
      'dough_type': '饼皮类型',
      'filling_type': '馅料类型',
      'goodMorning': '早上好',
      'goodAfternoon': '下午好',
      'goodEvening': '晚上好',
      'recipeSaveSuccessfulMsg': '食谱成功保存。',
      'category': '类别',
      'unknown': '未知',
      'quantity': '数量',
      'created_at': '创建日期',
      'used_in_tasks': '用于 {count} 个任务',
      'matched_dough_types': '匹配的饼皮类型',
      'matched_filling_types': '匹配的馅料类型',
      'validRecipeNameMsg': '请输入食谱名称。',
      'validRecipeTypeMsg': '请选择有效的饼皮类型。',
      'validFillingTypeMsg': '请选择馅料类型。',
      'validDoughRecipeMsg': '请选择饼皮食谱。',
      'validFillingRecipeMsg': '请选择馅料食谱。',
      'validIngredientNameMsg': '请输入配料名称。',
      'validIngredientAmountMsg': '请输入配料数量。',
      'validMatchedDoughTypesMsg': '请选择至少一个匹配的饼皮类型。',
      'validMatchedFillingTypesMsg': '请选择至少一个匹配的馅料类型。',
      'invalidNumber': '无效的数字。',
      'calculating': '计算中...',
      'calculateSave': '计算并保存',
      'msgNoRecipe': '无可用食谱',
      'changes_saved': '更改成功。',
      'failed_to_update_changes': '更新失败',
      'confirm_delete_task': '您确定要删除此任务吗？',
      'delete_task': '删除任务',
      'selectImage': '选择图片',
      'delete': '删除',
      'confirm_delete': '您确定要删除 {name} 吗？',
      'no_image_uploaded': '未上传图片',
      'completed': '已完成',
      'enter_comment': '在此输入评论...',
    },
  };

  static String get(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}
