class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'moonCakeCalculator': 'Moon Cake Calculator',
      'addNewTask': 'Which type of moon cake would you like to make?',
      'type': 'Type',
      'recipe_list_title': 'Recipes',
      'cantonese': 'Cantonese-style',
      'snowSkin': 'Snow skin',
      'selectRecipe': 'Select recipe',
      'doughRecipe': 'Dough Recipe',
      'fillingRecipe': 'Filling Recipe',
      'viewDetails': 'View Details',
      'fillingType': 'Filling type',
      'redBean': 'Red Bean',
      'lotusSeeds': 'Lotus Seed',
      'fiveNuts': 'Five Nuts',
      'pastryFillingRatio': 'Pastry/Filling Ratio',
      'size': 'Size (g)',
      'qty': 'Qty',
      'calculate': 'Calculate',
      'totalWeight': 'Total Weight:',
      'pastryWeight': 'Pastry Weight:',
      'fillingWeight': 'Filling Weight:',
      'goToList': 'Go to List',
      'recipes': 'Recipes',
      'addRecipe': 'Add Recipe',
      'name': 'Name',
      'style': 'Style',
      'ingredients': 'Ingredients',
      'ingredient': 'Ingredient',
      'amount': 'Amount',
      'save': 'Save',
      'saveTask': 'Save Task',
      'cancel': 'Cancel',
      'addIngredient': 'Add ingredient',
      'recipeSavedSuccessfully': 'Recipe saved successfully.',
      'createdLocalRecipesFile': 'Created local recipes file.',
      'addAtLeastOneIngredient': 'Add at least one ingredient.',
      'failedToSaveRecipe': 'Failed to save recipe:',
      'dough': 'Dough',
      'filling': 'Filling',
      'home': 'Home',
      'tasks': 'Tasks',
      'profile': 'Profile',
      'language': 'Language',
      'english': 'English',
      'chinese': 'Chinese',
      'noRecipesFound': 'No recipes found',
      'noRecipesAvailable': 'No recipes available',
      'back': 'Back',
      'close': 'Close',
      'noTasks': 'No tasks yet. Create one to get started!',
      'calculationResult': 'Calculation Result',
      'noIngredients': 'No ingredients.',
      'description': 'Description',
      'delete_recipe': 'Delete Recipe',
      'confirm_delete_recipe': 'Are you sure you want to delete {recipe_name}?',
      'comment': 'Comment',
      'reference_url': 'Reference URL',
      'dough_type': 'Dough Type',
      'filling_type': 'Filling Type',
      'goodMorning': 'Good Morning',
      'goodAfternoon': 'Good Afternoon',
      'goodEvening': 'Good Evening',
      'recipeSaveSuccessfulMsg':'Recipe saved successfully.',

    },
    'zh': {
      'moonCakeCalculator': '月饼计算器',
      'addNewTask': '今天您想做哪种类型的月饼？',
      'type': '类型',
      'recipe_list_title': '食谱',
      'cantonese': '广式月饼',
      'snowSkin': '冰皮月饼',
      'selectRecipe': '选择食谱',
      'doughRecipe': '饼皮食谱',
      'fillingRecipe': '馅料食谱',
      'viewDetails': '食谱详情',
      'fillingType': '馅料类型',
      'noFillingRecipes': '无馅料食谱可用，请添加馅料食谱。',
      'noDoughRecipes': '无饼皮食谱可用，请添加饼皮食谱。',
      'redBean': '红豆',
      'lotusSeeds': '莲子',
      'fiveNuts': '五仁',
      'pastryFillingRatio': '饼皮/馅料比例',
      'size': '月饼大小 (克)',
      'qty': '数量',
      'calculate': '计算饼皮及馅料配方',
      'totalWeight': '总重量:',
      'pastryWeight': '酥皮重量:',
      'fillingWeight': '馅料重量:',
      'goToList': '转到列表',
      'recipes': '食谱',
      'addRecipe': '添加食谱',
      'name': '名称',
      'style': '风格',
      'ingredients': '配料',
      'ingredient': '配料',
      'amount': '数量',
      'saveTask': '保存任务',
      'cancel': '取消',
      'addIngredient': '添加配料',
      'recipeSavedSuccessfully': '食谱保存成功。',
      'createdLocalRecipesFile': '创建本地食谱文件。',
      'addAtLeastOneIngredient': '至少添加一种原料。',
      'failedToSaveRecipe': '保存食谱失败：',
      'dough': '饼皮',
      'filling': '馅料',
      'home': '首页',
      'tasks': '任务',
      'profile': '个人资料',
      'language': '语言',
      'english': '英文',
      'chinese': '中文',
      'noRecipesFound': '未找到食谱',
      'noRecipesAvailable': '没有可用的食谱',
      'back': '返回',
      'close': '关闭',
      'noTasks': '还没有任务。创建一个任务开始！',
      'calculationResult': '配方计算结果',
      'noIngredients': '没有配方。',
      'description': '描述',
      'delete_recipe': '删除食谱',
      'confirm_delete_recipe': '确定要删除 {recipe_name} 吗？',
      'comment': '评论',
      'reference_url': '参考网址',
      'dough_type': '饼皮类型',
      'filling_type': '馅料类型',
      'goodMorning': '早上好',
      'goodAfternoon': '下午好',
      'goodEvening': '晚上好',
      'recipeSaveSuccessfulMsg':'食谱成功保存。'
    },
  };

  static String get(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}
